FROM node:18-alpine

WORKDIR /app

COPY ./go-next/package.json .
COPY ./go-next/package-lock.json .

RUN npm install

COPY ./go-next .

RUN npm run build

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "3000"]
