FROM node:20-alpine AS builder

WORKDIR /app

COPY ./go-next .
RUN npm install
RUN npm install @react-router/node
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
