services:
  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    environment:
      - DB_HOST=postgres_dev
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=gonext_dev
      - JWT_SECRET=debugPass
    depends_on:
      - postgres_dev
    networks:
      - gonext_network_dev

  postgres_dev:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gonext_dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - gonext_network_dev

  frontend_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - postgres_dev
    networks:
      - gonext_network_dev
    volumes:
      - ./frontend/go-next:/app
      - frontend_data_dev:/app/node_modules

volumes:
  postgres_data_dev:
  frontend_data_dev:

networks:
  gonext_network_dev:
    driver: bridge
